# Generated by Django 5.0.1 on 2024-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_remove_apikey_last_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calls_made', models.IntegerField(default=0)),
                ('calls_limit', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='Global API Key', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
