# Generated by Django 5.0.1 on 2024-11-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0003_globalapikey_delete_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalapikey',
            options={'verbose_name': 'Global API Key', 'verbose_name_plural': 'Global API Key'},
        ),
        migrations.RemoveField(
            model_name='globalapikey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='globalapikey',
            name='name',
        ),
    ]
