# Generated by Django 5.0.1 on 2024-11-01 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0004_alter_globalapikey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalapikey',
            options={},
        ),
        migrations.AddField(
            model_name='globalapikey',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
